import 'package:hive/hive.dart';
part 'book_entity.g.dart';
// This file is generated by Hive, a lightweight and fast key-value database.
@HiveType(typeId: 0)
// This class represents a book entity in the application.
class BookEntity {
  // The fields of the book entity are annotated with @HiveField to indicate
  // that they should be stored in the Hive database.
  @HiveField(0)
  final String bookId;
  @HiveField(1)
  final String? image;
  @HiveField(2)
  final String title;
  @HiveField(3)
  final String? outherName;
  @HiveField(4)
  final num? price;
  @HiveField(5)
  final num? rating;

  BookEntity({
    required this.bookId,
    required this.image,
    required this.title,
    required this.outherName,
    required this.price,
    required this.rating,
  });
}
